# Generated by Django 3.0.2 on 2020-01-30 10:33

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('firstApp', '0003_auto_20200130_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='User Name')),
                ('mobile_telephone', models.PositiveIntegerField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.'), django.core.validators.MaxLengthValidator], verbose_name='Mobile')),
                ('image', models.ImageField(blank=True, default='', upload_to='media/image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.CharField(choices=[('app', 'app'), ('card', 'card'), ('web', 'web')], max_length=256, verbose_name='Our Portfolio'),
        ),
    ]
