# Generated by Django 3.0.2 on 2020-01-30 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20200130_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile_telephone',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=18, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.'), django.core.validators.MaxLengthValidator], verbose_name='Mobile'),
        ),
    ]
