# Generated by Django 3.0.2 on 2020-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_auto_20200130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/user', verbose_name='Image'),
        ),
    ]
